ROOM1 = "corridor"
ROOM2 = "frontdeskoffice"
ROOM3 = "classroom2015"
ROOM4 = "projectroom3"
ROOM5 = "studylandscape"
ROOM6 = "lab03"
ROOM7 = "lab01"

ITEM_1 = "manual"
ITEM_2 = "battery"
ITEM_3 = "yellow keycard"
ITEM_4 = "hard disk"
ITEM_5 = "item5"
ITEM_6 = "password"
ITEM_7 = "item7"